### ISSUE TITLE
BUG: Vitis fails while executing driver Makefile (on Windows only) 

### ISSUE THREAD

**Issue by patrick-studer** [paulscherrerinstitute/vivadoIP_mem_test#2]
**I did not use this core but to be consistent with the other vivadoIP cores...**

Vitis 2020.1 fails when building platform/bsp...

Same issue as in [vivadoIP_power_sink](https://github.com/paulscherrerinstitute/vivadoIP_power_sink/issues/2).

**Comment by jonasppsi** [comment]
Thanks for updating.
